gradient_regularizers:
  discriminator:
    - name: Modified Orthogonal Regularizer
      class: weight_regularizers.ModifiedOrthogonalRegularizer
      params:
        regularization: 1e-4

  generator:
    - name: Modified Orthogonal Regularizer
      class: weight_regularizers.ModifiedOrthogonalRegularizer
      params:
        regularization: 1e-4


