defaults:
  - dataset: mnist
  - model: model
  - loss: ra_lsgan
  - loss_regularizers: loss_regularizers
  - gradient_regularizers: gradient_regularizers
  - trainer: default_trainer
  - training: training
  - logging: logging
  - dataloader: dataloader
  - optimizer: oadam


name: experiment
datasets_path: .datasets
checkpoints_path: .checkpoints
latent_dimension: 256
image_size: 128
spectral_normalization: True
instance_noise: True
alternation_interval: 1
resume_id: False
