defaults:
  - dataset: celeba_hq
  - model: model
  - loss: wgan
  - loss_regularizers: default_loss_regularizers
  - weight_regularizers: weight_regularizers
  - trainer: default_trainer
  - training: training
  - logging: logging
  - dataloader: dataloader
  - optimizer: oadam


name: experiment
datasets_path: /home/users/stachc/Code/gan-research/.datasets
checkpoints_path: /home/users/stachc/Code/gan-research/.checkpoints
latent_dimension: 256
image_size: 256
spectral_normalization: True
instance_noise: True
instance_noise_last_global_step: 75000
resume_id: False
