loss_regularizers:
  discriminator:
    - name: Linfinity gradient penalties # https://github.com/AlexiaJM/MaximumMarginGANs
      class: loss_regularizers.GradientPenalty
      params:
        log_as: gp
        center: 1
        coefficient: 20
        power: 2
        norm_type: linf
        penalty_type: hinge

  generator: []


