loss_regularizers:
  discriminator:
    - name: Linfinity gradient penalties # https://github.com/AlexiaJM/MaximumMarginGANs
      class: loss_regularizers.GradientPenalty
      params:
        log_as: gp
        center: 1
        coefficient: 20
        power: 1
        norm_type: linf
        penalty_type: hinge

    - name: 1 Centered GP # Original WGAN-GP
      class: loss_regularizers.GradientPenalty
      params:
        log_as: gp
        center: 1
        coefficient: 10
        power: 2
        norm_type: l2
        penalty_type: ls

    - name: 0 Centered GP
      class: loss_regularizers.GradientPenalty
      params:
        log_as: gp
        center: 0
        coefficient: 10
        power: 2
        norm_type: l2
        penalty_type: ls

    - name: Lipschitz Penalty # https://arxiv.org/abs/1709.08894
      class: loss_regularizers.GradientPenalty
      params:
        log_as: gp
        center: 1
        coefficient: 10
        power: 2
        norm_type: l2
        penalty_type: hinge

  generator: []


