loss_regularizers:
  discriminator:
    - name: Lipschitz Penalty
      class: loss_regularizers.LipschitzPenalty
      params:
        log_as: lp
        center: 0
        coefficient: 10
        power: 2

  generator: []


