loss_regularizers:
  discriminator: []

  generator:
    - name: Orthogonal Regularizer
      class: loss_regularizers.OrthogonalRegularizer
      params:
        log_as: g_orth
        regularization: 1e-6



